server:
  port: 8090

spring:
  application:
    name: wrlhblog


    #配置数据库连接.u
  datasource:
    username: root
    password: wxh564738
    url: jdbc:mysql://10.211.55.7/wrlhblog?useUnicode=true&characterEncoding=UTF-8&serverTimezone=Asia/Shanghai&useSSL=false
    type: com.alibaba.druid.pool.DruidDataSource
